### ISSUE TITLE
Render nothing in jupyter notebook[BUG] 

### ISSUE THREAD

**Issue by Guankuiliu** [msoechting/lexcube#3]
Hi Maximilian,

  Thank you for your excellent work. I have installed lexcube but encountered an issue - the images are not rendering (no error reported), and I'm not sure what's causing it.

![image](https://github.com/msoechting/lexcube/assets/43770509/6f8c9d6a-5767-4517-be20-cd4d15bc40b8)

![image](https://github.com/msoechting/lexcube/assets/43770509/a4000d1b-8763-47db-b1e8-7b9f47a4ffda)

**Comment by msoechting** [comment]
Hi Guankui, thanks for your report! What IDE/program are you using to display Jupyter notebook content? Also, is it possible to retrieve any error message, e.g., through a web inspector? Thanks 😃

**Comment by Guankuiliu** [comment]
Here it is:
[localhost-1711090551706.log](https://github.com/msoechting/lexcube/files/14718681/localhost-1711090551706.log)

**Comment by msoechting** [comment]
Hi @Guankuiliu, thanks for the log! I have an idea on what might be the issue. Which program are you using though? I would need to test my solution locally and don't recognize the GUI in your screenshot 😄

**Comment by msoechting** [comment]
Hi @Guankuiliu, 

Your requirements.txt does not contain jupyter_server or jupyterthemes, I am not sure the requirements.txt is complete?

I could not reproduce the issue in a Python virtualenv with Jupyter Notebook 7.1.2 or 6.0.0 with your requirements and the "oceans16" theme installed on Windows 11:
![grafik](https://github.com/msoechting/lexcube/assets/6423697/0d345086-e872-4440-959d-698f9808c9bd)

**Ideas for fixing:**
1. Try "trusting" the environment (top-right, next to the kernel selection)
2. Try upgrading Jupyter Notebook
3. Try using Jupyter Lab (`jupyter lab` instead of `jupyter notebook`)
4. Try installing widgetsnbextension or ipywidgets 4.0 (based on a warning I got in my web console)
5. Sometimes the extension JavaScript code is fetched from NPM instead of locally. However, I saw that the default NPM registry is blocked in China, maybe this is a problem? (https://stackoverflow.com/questions/22764407/npm-install-goes-to-dead-in-china)
6. Try in a fresh environment and run `pip install lexcube`, which also installs the latest compatible Jupyter version.

If the issue persists, you can also provide:
1. Exact browser version you are using (three dot menu -> "About Google Chrome")
2. Python version (`python --version`)

**Comment by msoechting** [comment]
Hi @Guankuiliu. Some general bugs have been fixed since the last time you used Lexcube. Please try again with the latest version and let me know if it works out.

**Comment by Guankuiliu** [comment]
Hi @msoechting. 
In VSCode, everything works fine. After reinstalling, the issue still persists in Chrome. I think it might be a problem with my system itself.
![image](https://github.com/user-attachments/assets/e19f08c5-bfce-4771-8fe3-cad1ddea0edb)
![image](https://github.com/user-attachments/assets/38739bde-5340-47ec-961d-cba398a98615)

**Comment by msoechting** [comment]
Thanks for the reply. In Chrome, do you get any error in the developer console (F12)?

**Comment by msoechting** [comment]
I think something went wrong with the 0.4.18 published packages. I could reproduce the error in Google Chrome; the NPM 0.4.18 package contained "0.4.17" as a version string, I guess that was the problem... I published 0.4.19 and it works in Chrome again! Let me know if 0.4.19 also works for you 😄

**Comment by Guankuiliu** [comment]
> Thanks for the reply. In Chrome, do you get any error in the developer console (F12)?

Actually, I noticed multiple errors in the Chrome developer console, but since I deleted that conda environment, I'm no longer able to reproduce the errors.

**Comment by Guankuiliu** [comment]
> I think something went wrong with the 0.4.18 published packages. I could reproduce the error in Google Chrome; the NPM 0.4.18 package contained "0.4.17" as a version string, I guess that was the problem... I published 0.4.19 and it works in Chrome again! Let me know if 0.4.19 also works for you 😄

Hi @msoechting, I just created a new conda environment, and now everything is working fine with Jupyter Notebook in Chrome.
![image](https://github.com/user-attachments/assets/6671e350-5195-4ac6-9f7b-5250bf441ce9)

**Comment by msoechting** [comment]
Great to hear! Thank you for reporting the issues.
